sonar.projectKey=fiap-soat-tc
sonar.organization=Software_Architecture_11SOAT

sonar.projectName=webhook-service

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.coverage.exclusions=\
**/adapters/out/client/request/**,\
**/mapper/**,\
**/adapters/**/handler/**,\
**/config/**,\
**/*Application.java