apiVersion: v1
kind: Service
metadata:
  name: deivi-motors-service
  namespace: deivi-motors-k8s
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /deivi_motors/actuator/health
    alb.ingress.kubernetes.io/success-codes: "200"
spec:
  type: ClusterIP
  selector:
    app: deivi-motors
  ports:
    - port: 8080
      targetPort: 8080
