apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: 404234478011.dkr.ecr.us-east-1.amazonaws.com/deivimotors-service
    newTag: latest
  - name: 404234478011.dkr.ecr.us-east-1.amazonaws.com/deivimotors-webhook
    newTag: latest

resources:
  - deivi-motors-deployment.yaml
  - deivi-motors-service.yaml
  - webhook-deployment.yaml
  - webhook-service.yaml

