apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: deivi-motors-k8s
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /webhook/actuator/health
    alb.ingress.kubernetes.io/success-codes: "200"
spec:
  type: ClusterIP
  selector:
    app: webhook
  ports:
    - port: 9090
      targetPort: 9090